name: CI - Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build & Test on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential

      - name: Build the project
        run: make

  test-file:
    name: Test File Logging
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential

      - name: Run Example Program (FILE)
        run: ./example_app

      - name: Verify Log File Existence
        run: ls -lah logfile.txt || echo "Log file not found"

      - name: Display Log File Contents
        run: cat logfile.txt || echo "Log file is empty"

  test-stdout:
    name: Test STDOUT Logging
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential

      - name: Run Example Program (STDOUT)
        run: ./example_app | tee console_output.log

      - name: Display Console Output
        run: cat console_output.log || echo "Console output file not found"

  test-journald:
    name: Test Systemd Journal Logging
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential systemd

      - name: Run Example Program (JOURNALD)
        run: |
          sudo ./example_app &
          sleep 2  # Give Systemd time to register logs

      - name: Verify Systemd Journal Logs
        run: |
          sudo journalctl --no-pager --output=short-iso-precise | grep "System initialized" || echo "Journalctl log not found"

  cross-compile:
    name: Test Cross-Compilation for Embedded Linux
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cross-compiler
        run: sudo apt install -y gcc-arm-linux-gnueabi

      - name: Cross-Compile for ARM
        run: make CC=arm-linux-gnueabi-gcc
